name: Build Flatpak CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_deps_base:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v5

      - name: "Read YAML"
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_sdk
        with:
          config: ${{ github.workspace }}/elements/freedesktop-sdk.bst

      - name: "Check Buildstream Cache"
        uses: actions/cache/restore@v5
        id: cache-lookup
        with:
          path: ~/.cache/buildstream
          key: ${{ steps.read_sdk.outputs['sources.0.ref'] }}-base
          lookup-only: true

      - name: "Install BuildStream2"
        if: steps.cache-lookup.outputs.cache-hit != 'true'
        run: |
          sudo dnf group install -y c-development
          sudo dnf install -y flatpak bubblewrap fuse3 git lzip patch python3-devel python3-pip fuse3 fuse3-devel node
          pip install buildstream buildstream-plugins buildstream-external bst-plugins-experimental dulwich==0.24.10

# Try to restore the most recent build stream cache
      - name: "Build dependencies to reduce job size (base)"
        if: steps.cache-lookup.outputs.cache-hit != 'true'
        run: bst build freedesktop-sdk.bst:bootstrap-import.bst freedesktop-sdk.bst:components/ostree-minimal.bst freedesktop-sdk.bst:components/appstream-minimal.bst

      - name: "Save Buildstream Cache"
        if: steps.cache-lookup.outputs.cache-hit != 'true' && success()
        uses: actions/cache/save@v5
        with:
          path: ~/.cache/buildstream
          key: ${{ steps.cache-lookup.outputs.cache-primary-key }}

  build_deps_sdk:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    needs: build_deps_base
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v5

      - name: "Read YAML"
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_sdk
        with:
          config: ${{ github.workspace }}/elements/freedesktop-sdk.bst

      - name: "Check Buildstream Cache"
        uses: actions/cache/restore@v5
        id: cache-lookup
        with:
          path: ~/.cache/buildstream
          key: ${{ steps.read_sdk.outputs['sources.0.ref'] }}-sdk
          lookup-only: true

      - name: "Restore Buildstream Cache"
        uses: actions/cache/restore@v5
        id: cache-restore
        if: steps.cache-lookup.outputs.cache-hit != 'true'
        with:
          path: ~/.cache/buildstream
          key: ${{ steps.read_sdk.outputs['sources.0.ref'] }}-base
          fail-on-cache-miss: true

      - name: "Install BuildStream2"
        if: steps.cache-lookup.outputs.cache-hit != 'true'
        run: |
          sudo dnf group install -y c-development
          sudo dnf install -y flatpak bubblewrap fuse3 git lzip patch python3-devel python3-pip fuse3 fuse3-devel node
          pip install buildstream buildstream-plugins buildstream-external bst-plugins-experimental dulwich==0.24.10

# Try to restore the most recent build stream cache
      - name: "Build dependencies to reduce job size (SDK)"
        if: steps.cache-lookup.outputs.cache-hit != 'true'
        run: bst build freedesktop-sdk.bst:sdk.bst

      - name: "Save Buildstream Cache (SDK)"
        if: steps.cache-lookup.outputs.cache-hit != 'true' && success()
        uses: actions/cache/save@v5
        with:
          path: ~/.cache/buildstream
          key: ${{ steps.cache-lookup.outputs.cache-primary-key }}

  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    needs: build_deps_sdk
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v5

      - name: "Read YAML"
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_sdk
        with:
          config: ${{ github.workspace }}/elements/freedesktop-sdk.bst

      - name: "Restore Buildstream Cache"
        uses: actions/cache/restore@v5
        id: restore-cache
        with:
          path: ~/.cache/buildstream
          key: ${{ runner.os }}-bst-${{ hashFiles('elements/*.bst') }}
          restore-keys: |
            ${{ steps.read_sdk.outputs['sources.0.ref'] }}-sdk
          fail-on-cache-miss: true

      - name: "Install BuildStream2"
        run: |
          sudo dnf group install -y c-development
          sudo dnf install -y flatpak bubblewrap fuse3 git lzip patch python3-devel python3-pip fuse3 fuse3-devel node
          pip install buildstream buildstream-plugins buildstream-external bst-plugins-experimental dulwich==0.24.10

      - name: "Build .bst file"
        run: bst build rocm-flatpak.bst

      - name: "Save Buildstream Cache (SDK)"
        if: steps.restore-cache.outputs.cache-primary-key != steps.restore-cache.outputs.cache-matched-key && success()
        uses: actions/cache/save@v5
        with:
          path: ~/.cache/buildstream
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

      - name: "Bst Artifact"
        run: bst artifact checkout --directory ./rocm-repo rocm-flatpak.bst

      - name: "Add Flatpak Remote"
        run: flatpak remote-add --user rocm-repo ./rocm-repo --no-gpg-verify

      - name: "Install Flatpak"
        run: flatpak install -y --user org.freedesktop.Platform.GL.ROCm

      - name: "Build Flatpak"
        run: flatpak build-bundle --runtime ./rocm-repo rocm.flatpak org.freedesktop.Platform.GL.ROCm 23.08

      - name: "Release to Github"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rocm.flatpak"
          tag: "latest"
          commit: ${{ github.sha }}
          allowUpdates: true
